# Generated by Django 5.1.7 on 2025-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
